<?php

declare(strict_types=1);

namespace Otis22\VetmanagerConversations;

use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Drivers\Tests\FakeDriver;
use BotMan\Studio\Testing\BotManTester;
use PHPUnit\Framework\TestCase;

abstract class BotManTestCase extends TestCase
{
    /**
     * @var BotManTester
     */
    protected $tester;

    /**
     * @var FakeDriver
     */
    protected $driver;

    /**
     * @var BotMan
     */
    protected $botman;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->driver = new FakeDriver();

        $this->botman = BotManFactory::create([]);
        $this->botman->setDriver($this->driver);
        $this->tester = new BotManTester($this->botman, $this->driver);
    }
}
